//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.07 at 07:55:37 PM IST 
//


package com.home.jixb.cust.bind;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.aspire.oms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.aspire.oms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MySimpleOrder }
     * 
     */
    public MySimpleOrder createMySimpleOrder() {
        return new MySimpleOrder();
    }

    /**
     * Create an instance of {@link MyItem }
     * 
     */
    public MyItem createMyItem() {
        return new MyItem();
    }

    /**
     * Create an instance of {@link MyAddress }
     * 
     */
    public MyAddress createMyAddress() {
        return new MyAddress();
    }

    /**
     * Create an instance of {@link Items }
     * 
     */
    public Items createItems() {
        return new Items();
    }

}
